#!/bin/bash  
# description: TomEE Start Stop Restart  
# processname: tomee  
# chkconfig: 234 20 80  
JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk-armhf  
export JAVA_HOME  
PATH=$JAVA_HOME/bin:$PATH  
export PATH  
DERBY_HOME=/opt/javadb
    case $1 in  
	start)  
    sh $DERBY_HOME/bin/startNetworkServer -h 127.0.0.1 -p 1527
    ;;   
    stop)     
    sh $DERBY_HOME/bin/stopNetworkServer -h 127.0.0.1 -p 1527
    ;;   
    restart)  
    sh $DERBY_HOME/bin/stopNetworkServer -h 127.0.0.1 -p 1527
    sh $DERBY_HOME/bin/startNetworkServer -h 127.0.0.1 -p 1527
    ;;   
    esac      
    exit 0  
