#!/bin/bash  
# description: TomEE Start Stop Restart  
# processname: tomee  
# chkconfig: 234 20 80  
JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk-armhf  
export JAVA_HOME  
PATH=$JAVA_HOME/bin:$PATH  
export PATH  
CATALINA_HOME=/opt/tomee
    case $1 in  
	start)  
    sh $CATALINA_HOME/bin/startup.sh  
    ;;   
    stop)     
    sh $CATALINA_HOME/bin/shutdown.sh  
    ;;   
    restart)  
    sh $CATALINA_HOME/bin/shutdown.sh  
    sh $CATALINA_HOME/bin/startup.sh  
    ;;   
    esac      
    exit 0  
